# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6501c4789c053f4ac9e57bde9b3045d729b9e4cced69fb7be4c08fd6694a02685c852a7982377003621464852d6a94c32ec2f5034456305d6002f9516519ea9

test:
  secret_key_base: 6fb8fa5b3e138039873463f3f2917eb39c6175f28dd9d6f1062ac4c91d50c10735c3b3ebc568a00c72f082dc00917af3f80b6aedbbc50cdb8c9445d7bbf73946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
